### ISSUE TITLE
Error when building make in the root directory

### ISSUE THREAD

**Issue by lenhatquang2512** [lukezsmith/stm32-dev#1]
Hi, thank you for your repository.

I tried to build your project and dev container in Vscode loaded your package successfully. I followed your guide in README but I got this error :

![image](https://github.com/lukezsmith/stm32-dev/assets/72292146/327e0c90-28a1-42d1-9488-5185feede02e)

Can you tell me how to solve this ? Im using Wsl (subsystem Linux) with my Windows machine. Thank you a lot.

**Comment by lenhatquang2512** [comment]
No worries problem is solved. I changed these 2 lines in the Makefile to the correct path CMake:

![image](https://github.com/lukezsmith/stm32-dev/assets/72292146/5f1c5404-59d8-47d4-86f4-f39e77faf204)

And then changed line 4 in gcc-arm-none-aebi.cmake to correct the ARM GNU toolchain path:

![image](https://github.com/lukezsmith/stm32-dev/assets/72292146/8847983c-0099-4fa9-9959-a566f759c20d)

Finally, to enable the Intellisense, I changed lines 13 and 30 of c_cpp_properties.json to the correct ARM Toolchain path, and I successfully built your template.

![image](https://github.com/lukezsmith/stm32-dev/assets/72292146/0212d056-8b77-4336-a08e-2c3fae1ff27d)

Anyway, thank you for the great template! I was trying to find a method that I can program STM32 in VSCode without using PlatformIO and integrate Google Test. Your repo is the perfect solution.

**Comment by lukezsmith** [comment]
> No worries problem is solved. I changed these 2 lines in the Makefile to the correct path CMake:
> 
> ![image](https://user-images.githubusercontent.com/72292146/253146776-5f1c5404-59d8-47d4-86f4-f39e77faf204.png)
> 
> And then changed line 4 in gcc-arm-none-aebi.cmake to correct the ARM GNU toolchain path:
> 
> ![image](https://user-images.githubusercontent.com/72292146/253147049-8847983c-0099-4fa9-9959-a566f759c20d.png)
> 
> Finally, to enable the Intellisense, I changed lines 13 and 30 of c_cpp_properties.json to the correct ARM Toolchain path, and I successfully built your template.
> 
> ![image](https://user-images.githubusercontent.com/72292146/253147386-0212d056-8b77-4336-a08e-2c3fae1ff27d.png)
> 
> Anyway, thank you for the great template! I was trying to find a method that I can program STM32 in VSCode without using PlatformIO and integrate Google Test. Your repo is the perfect solution.

Sorry for the late response, glad to hear you fixed it. I will add a disclaimer/message in the README about setting the correct paths.
